### ISSUE TITLE
Prevent `master_proxy` from starting when a Mix Task is called from the command line

### ISSUE THREAD

**Issue by mikehostetler** [jesseshieh/master_proxy#8]
We're using `master_proxy` in an internal project. We have a few custom mix tasks to manage data imports.

When we call those custom mix tasks, both Phoenix endpoints (we have two) start up.  Is there a way to prevent `master_proxy` from starting up when calling a custom mix task?

**Comment by jesseshieh** [comment]
Good question! I think the way phoenix does it is with a `server: true`. By default, it's set to false, and the only command that enables it is `mix phx.server`. When using distillery or elixir releases, you have to explicitly set it to true somewhere such as your prod.exs. We could try and do the same thing for master_proxy. I'd be happy to merge a pull request doing so!

**Comment by axelson** [comment]
One approach is to check `Application.get_env(:phoenix, :serve_endpoints)`, used by this gist:

https://gist.github.com/cblavier/0c2cf3f101d82c32503774f179a66a3f#file-application-ex-L57-L58

**Comment by peaceful-james** [comment]
This is a hacky workaround for devs like me who just need this working today. My only problem is that master_proxy tries to run twice and the port clashes. Instead of trying to stop it, I'm going to let it run, just on a different port. This is not an elegant solution.

Wherever you set your master_proxy config ( I set mine in `runtime.exs`), change the port, using the trick mentioned by @axelson :

```elixir
# TODO undo the "port" hack when we can disable master_proxy during, say, 'mix test'. See https://github.com/jesseshieh/master_proxy/issues/8
master_proxy_http_port = if Application.get_env(:phoenix, :serve_endpoints), do: 4000, else: 4099

config :master_proxy,
  http: [:inet6, port: master_proxy_http_port],
  backends: [
    %{
      host: ~r/localhost/,
      phoenix_endpoint: MyAppWeb.Endpoint
    }
  ]
```
